[package]
name = "xorb"
version = "0.1.0"
edition = "2024"

[dependencies]
ignore = "0.4"
arboard = "3"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false

[profile.release-small]
inherits = "release"
opt-level = "z"

[profile.dev]
opt-level = 0
debug = true


